@base_url = http://localhost:8080/api/accounts

### Get Account Details
GET {{base_url}}/6aaab27131ff376d7baa5649

###

### Create Account
POST http://localhost:8080/api/accounts
Content-Type: application/json

{
  "userId": "6aaab013599f3711e0fc059c",
  "balance": 0,
  "accountType": "SAVINGS"
}

###

### Deposit Money
POST {{base_url}}/6aaab27131ff376d7baa5649/deposit/200

###

### Withdraw Money
POST {{base_url}}/6aaab27131ff376d7baa5649/withdraw/100

###

### Get Transaction History
GET {{base_url}}/6aaab27131ff376d7baa5649/transactions