@base_url = http://localhost:8080/api/accounts

### Get Account Details
GET {{base_url}}/6aaaba588e5df6d33d46e9b5

###

### Create Account
POST http://localhost:8080/api/accounts
Content-Type: application/json

{
  "userId": "6aaaba0e8e5df6d33d46e9b3",
  "balance": 0,
  "accountType": "SAVINGS"
}

###

### Deposit Money
POST {{base_url}}/6aaaba588e5df6d33d46e9b5/deposit/200

###

### Withdraw Money
POST {{base_url}}/6aaaba588e5df6d33d46e9b5/withdraw/100

###

### Get Transaction History
GET {{base_url}}/6aaaba588e5df6d33d46e9b5/transactions