@base_url = http://localhost:8080/api/users

### Get All Users
GET {{base_url}}

###

### Get User By ID
GET {{base_url}}/6aaaba0e8e5df6d33d46e9b3

###

### Create User
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "jane@gmail.com"
}

###

### Update User

PUT {{base_url}}/6aaaba0e8e5df6d33d46e9b3
Content-Type: application/json

{
  "name": "Jane Updated",
  "email": "jane.updated@gmail.com"
}

###

### Delete User

DELETE {{base_url}}/6aaaba0e8e5df6d33d46e9b3